Repository decentraland/explorer-desktop, pull requests merged in 2022-08, with the labels that each got.

#367 Release 2022-08-03
  unity-renderer-desktop/Packages/packages-lock.json
Labels: ready for review, release

#368 Release 2022-08-09
  unity-renderer-desktop/Packages/packages-lock.json
Labels: release

#374 Release 2022-08-25
  unity-renderer-desktop/Packages/packages-lock.json
Labels: ready for review

#376 release: revert "Release 2022-08-31 (#375)"
  unity-renderer-desktop/Packages/manifest.json
  unity-renderer-desktop/Packages/packages-lock.json
  unity-renderer-desktop/TestResources/GLB/gltfshape-asset-bundle-colliders-no-renderers.glb
Labels: ready for review
